#========================================
# Test profile settings (IT tests)
#========================================
logging:
  level:
    root: INFO
spring:
  main:
    banner-mode: 'off'
  security:
    oauth2:
      client:
        provider:
          employee:
            token-uri: http://localhost:${wiremock.server.port}/token
          party:
            token-uri: http://localhost:${wiremock.server.port}/token
        registration:
          employee:
            client-id: the-client-id
            client-secret: the-client-secret
          party:
            client-id: the-client-id
            client-secret: the-client-secret
integration:
  lifecare-ec:
    url: http://localhost:${wiremock.server.port}/lifecare-ec
    domain: it-domain
    key: it-key
  lifecare-fc:
    url: http://localhost:${wiremock.server.port}/lifecare-fc
    domain: it-domain
    key: it-key
  employee:
    url: http://localhost:${wiremock.server.port}/employee
  party:
    url: http://localhost:${wiremock.server.port}/party
