#========================================
# Test profile settings (junit tests)
#========================================
logging:
  level:
    root: DEBUG
integration:
  lifecare-ec:
    url: http://lifecareec.url
    domain: junit-domain
    key: junit-key
