application-production.yaml: |-
  integration:
    lifecare-ec:
      url: https://lifecare-ext.sundsvall.se/WE.EC.Integration.Host
      domain: override-me
    lifecare-fc:
      url: https://lifecare-ext.sundsvall.se/WESE.FC.Api.FC
      domain: override-me
    party:
      url: https://api.sundsvall.se/party/2.0

  spring:
    security:
      oauth2:
        client:
          provider:
            party:
              token-uri: https://api.sundsvall.se/token
