integration.lifecare-ec.key: b3ZlcnJpZGUtbWU=
integration.lifecare-fc.key: b3ZlcnJpZGUtbWU=
spring.security.oauth2.client.registration.party.client-id: b3ZlcnJpZGUtbWU=
spring.security.oauth2.client.registration.party.client-secret: b3ZlcnJpZGUtbWU=
