apiVersion: v2
name: lifecare-integrator-pipeline
description: A Tekton Helm chart for api-service-lifecare-integrator

type: application
version: 0.1.0

dependencies:
  - name: spring-boot-pipeline
    version: ^3.0.0
    repository: http://nexus.sundsvall.se/repository/sundsvall-helm/
