spring-boot-chart:
  appName: lifecare-integrator
  appVersion: "1.0"
  namespace: af-lifecare-integrator

  networkPolicy:
    allowedSources:
      - "af-springbootadmin.spring-boot-admin"

  image:
    repository: "evil.sundsvall.se/utvecklingsfabriken"
    sha: "sha256:0000000000000000000000000000000000000000000000000000000000000000"

  resources:
    limits:
      memory: 1024Mi
